languageCode = "en-us"
defaultContentLanguage = "en"
enableRobotsTXT = false
enableEmoji = true

theme = "almeida-cv"
disableKinds = ["page", "section", "taxonomy", "term", "RSS", "sitemap"]

#baseURL = "https://example.com/"
title = "Maksim Losev CV"

[params]
enableMetaTags = false
colorLight = "#F5F5F5"
colorDark = "#202020"
colorPageBackground = "#d0d0d0"
colorPrimary = "#303030"
colorSecondary = "#b0b0b0"
colorIconPrimary = "#202020"
colorIconBackground = "#f4bf75"
colorRightColumnBackground = "#e0e0e0"
colorRightColumnHeadingText = "#151515"
colorRightColumnBodyText = "#151515"
colorRightColumnIconPrimary = "#ffffff"
colorRightColumnIconBackground = "#f4bf75"
pages = 2

swapColumns = false
